namespace DPloy;

public class DeployerConfig {

    public string BotToken { get; set; } = "";

    /// <summary>The guild where slash commands are registered.</summary>
    public ulong GuildId { get; set; }

    /// <summary>Discord user IDs allowed to run /deploy commands.</summary>
    public List<string> AdminUserIds { get; set; } = [];

    /// <summary>Channel where live deployment progress messages are posted and edited.</summary>
    public ulong DeployChannelId { get; set; }

    /// <summary>State directory: state.json, work/ clones, pending-switch markers.</summary>
    public string DataPath { get; set; } = "/var/lib/d-ploy";

    /// <summary>SSH URL of the NixOS infra repo that flake.lock bumps are pushed to.</summary>
    public string InfraRepo { get; set; } = "";

    /// <summary>Port for the GitHub webhook listener (POST /hook). Disabled when null.</summary>
    public int? WebhookPort { get; set; }

    /// <summary>Bearer secret for webhook requests.</summary>
    public string? WebhookSecret { get; set; }

    /// <summary>Interval for the periodic reconcile scan — the safety-net desired/deployed
    /// comparison, not release checking. Also the fallback release-check cadence when
    /// UpdateCheckSchedule is unset.</summary>
    public int ReconcileIntervalMinutes { get; set; } = 5;

    /// <summary>
    /// systemd OnCalendar expression (see `systemd-analyze calendar`) controlling when the
    /// release-check tag poll runs — e.g. "daily", "*-*-* 03:00:00", "Mon 09:00". Lets update
    /// checks happen on a real schedule instead of depending on a GitHub webhook being wired
    /// up. Unset (default) falls back to polling every ReconcileIntervalMinutes, same as before.
    /// </summary>
    public string? UpdateCheckSchedule { get; set; }

    public Dictionary<string, ProjectConfig> Projects { get; set; } = [];
}

public class ProjectConfig {
    public string DisplayName { get; set; } = "";

    /// <summary>SSH URL of the project repo (tag lookups via git ls-remote).</summary>
    public string RepoUrl { get; set; } = "";

    /// <summary>Input name in the infra flake that `nix flake update` bumps.</summary>
    public string InfraInputName { get; set; } = "";

    /// <summary>Path to the sudo-whitelisted d-ploy-switch-{key} wrapper (generated by the NixOS module).</summary>
    public string SwitchScriptPath { get; set; } = "";

    /// <summary>systemd units that must be active after a switch for the deploy to count as healthy.</summary>
    public List<string> HealthUnits { get; set; } = [];

    /// <summary>How long to watch HealthUnits after a switch before declaring success.</summary>
    public int SoakSeconds { get; set; } = 60;

    /// <summary>
    /// True for the project that IS d-ploy: the switch restarts this daemon, so it runs
    /// detached (systemd-run) with a pending-switch marker finalized on next startup.
    /// </summary>
    public bool SelfUpdate { get; set; }
}
