namespace DPloy;

public class DeployerConfig {

    public string BotToken { get; set; } = "";

    /// <summary>The guild where slash commands are registered.</summary>
    public ulong GuildId { get; set; }

    /// <summary>Discord user IDs allowed to run /deploy commands.</summary>
    public List<string> AdminUserIds { get; set; } = [];

    /// <summary>Discord role IDs allowed to run /deploy commands — anyone holding one of
    /// these roles is authorized, on top of AdminUserIds. Only checked in a guild context
    /// (roles don't exist in DMs); a user invoking /deploy via DM still needs to be in
    /// AdminUserIds.</summary>
    public List<string> AdminRoleIds { get; set; } = [];

    /// <summary>Channel where live deployment progress messages are posted and edited.</summary>
    public ulong DeployChannelId { get; set; }

    /// <summary>Guild channels /deploy commands may be used in — keeps every command and its
    /// result in one predictable, visible place for an audit trail. Only enforced for the
    /// home guild — a DM has no "designated channel" concept, and is the only other place
    /// /deploy works at all (it's deliberately not user-installable; see DeployModule's doc
    /// comment). Empty/unset falls back to just DeployChannelId.</summary>
    public List<string> CommandChannelIds { get; set; } = [];

    /// <summary>State directory: state.json, work/ clones, pending-switch markers.</summary>
    public string DataPath { get; set; } = "/var/lib/d-ploy";

    /// <summary>SSH URL of the NixOS infra repo that flake.lock bumps are pushed to.</summary>
    public string InfraRepo { get; set; } = "";

    /// <summary>Port for the GitHub webhook listener (POST /hook). Disabled when null.</summary>
    public int? WebhookPort { get; set; }

    /// <summary>Bearer secret for webhook requests.</summary>
    public string? WebhookSecret { get; set; }

    /// <summary>Interval for the periodic reconcile scan — the safety-net desired/deployed
    /// comparison, not release checking. Also the fallback release-check cadence when
    /// UpdateCheckSchedule is unset.</summary>
    public int ReconcileIntervalMinutes { get; set; } = 5;

    /// <summary>
    /// systemd OnCalendar expression (see `systemd-analyze calendar`) controlling when the
    /// release-check tag poll runs — e.g. "daily", "*-*-* 03:00:00", "Mon 09:00". Interpreted
    /// in the host's local timezone (NixOS `time.timeZone`), not UTC. Lets update checks
    /// happen on a real schedule instead of depending on a GitHub webhook being wired up.
    /// Defaults to Monday at 12:30pm local time; set to null/empty to fall back to polling
    /// every ReconcileIntervalMinutes instead.
    /// </summary>
    public string? UpdateCheckSchedule { get; set; } = "Mon 12:30";

    public Dictionary<string, ProjectConfig> Projects { get; set; } = [];
}

public class ProjectConfig {
    public string DisplayName { get; set; } = "";

    /// <summary>SSH URL of the project repo (tag lookups via git ls-remote).</summary>
    public string RepoUrl { get; set; } = "";

    /// <summary>Input name in the infra flake that `nix flake update` bumps.</summary>
    public string InfraInputName { get; set; } = "";

    /// <summary>nixosConfigurations attribute this project switches to. Two projects sharing
    /// the same NixosAttr are switching the same host config, so the Reconciler batches them
    /// into one shared clone/bump/switch/soak pass when both are due at once — see
    /// Reconciler.ConvergeBatchAsync. Never used to build a command itself (SwitchScriptPath
    /// already bakes it in); only used to decide what can safely be batched together.</summary>
    public string NixosAttr { get; set; } = "";

    /// <summary>Path to the sudo-whitelisted d-ploy-switch-{key} wrapper (generated by the NixOS module).</summary>
    public string SwitchScriptPath { get; set; } = "";

    /// <summary>systemd units that must be active after a switch for the deploy to count as healthy.</summary>
    public List<string> HealthUnits { get; set; } = [];

    /// <summary>How long to watch HealthUnits after a switch before declaring success.</summary>
    public int SoakSeconds { get; set; } = 60;

    /// <summary>
    /// True for the project that IS d-ploy: the switch restarts this daemon, so it runs
    /// detached (systemd-run) with a pending-switch marker finalized on next startup.
    /// </summary>
    public bool SelfUpdate { get; set; }
}
